### ISSUE TITLE
Cannot deploy the react-example

### ISSUE THREAD

**Issue by dariarse** [izaera/liferay-npm-examples#2]
Hi all! 

I'm trying to deploy the react-example in Liferay DXP but after building the react part I cannot deploy it from the view.jsp just the way you suggest to do it. **In my view.jsp I have**:
```<%@ include file="/init.jsp" %>

<aui:script require="liferay-npm-example-react-old@1.0.1">
</aui:script>

<div id="liferay-npm-example-react-root"></div>
```
But then all I see is the portlet without the react app. And the console shows **"Failed to get resource"**. I've found that the react transpiled script is in 
```
http://localhost:8080/combo/?browserId=other&/o/liferay-npm-example-react-old/lib/index.es.js
```

I do not know how to manage to get things work. **Could anyone give me a hint please?** @izaera Do you have any ideas?
Thanks!

**Comment by izaera** [comment]
@dariarse This project if only meant to work in the current development version of Liferay portal as it is a work in progress for the next version. It won't work in Liferay 7.

I have updated the README to avoid future misunderstandings. Sorry :-(
